name: "paddleocr"
backend: "python"
max_batch_size: 2
input [
  {
    name: "INPUT"
    data_type: TYPE_BYTES
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_BYTES
    dims: [ -1 ]
  }
]
instance_group [
  { kind: KIND_GPU }
]
